Organisms-Top
shinonome-inc/Kotaro-frontend-basic-last-assignment pull request #10
Opened 2022-12-06 06:34 UTC by Kotaro0722

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[](https://62c82af834e6e12f9fe007c7-rwdaxoocmv.chromatic.com/?path=/story/organisms-top--top)

2022-12-10 13:11 UTC, tomu-fujikawa reviewed
おそらくmdの画面サイズのときのスタイルを書き忘れていると思うので追加お願いします！

2022-12-10 13:11 UTC, tomu-fujikawa commented on src/components/organisms/top/top.scss
> +      height: 700px;
これだとlg未満のときには画面からはみ出して表示されてしまいます！
md以下のときは画像の高さは360px固定です！

2022-12-13 08:06 UTC, SakaueYae reviewed
![image](https://user-images.githubusercontent.com/101164626/207256034-07a4ab10-fafa-46d9-bcc7-2c950887a613.png)
![image](https://user-images.githubusercontent.com/101164626/207256396-1b858c69-1ca7-4ad0-8f0c-21fba1f2e126.png)
sm、mdのときは画像が枠からはみ出してしまっているため、高さは360pxを保ったまま枠内に画像が表示されるよう調整してみてください！
lgのときは見た目は問題ないですが、xlのときは画像のように右側に空白ができてしまっています。lg以上のときは画像の比率を保ったまま横幅いっぱいに表示されるよう修正してみてください！
これらを修正する際にbackgroundプロパティが役に立つと思います！

2022-12-13 08:06 UTC, SakaueYae commented on src/components/organisms/top/top.html
> +    <img src="../../../img/top.jpg" alt="" />
これはcssの方でbackground-imageで背景画像として指定した方が、他のbackgroundプロパティを利用することができ便利だと思います！
参考：https://developer.mozilla.org/ja/docs/Web/CSS/background

2022-12-13 08:06 UTC, SakaueYae commented on src/components/organisms/top/top.html
> +<div class="top">
organismsレベルの大きなかたまりはsectionタグを使うと良いと思います。

2022-12-13 08:06 UTC, SakaueYae commented on src/components/organisms/top/top.scss
> +      height: 211px;
![スクリーンショット_20221213_163851](https://user-images.githubusercontent.com/101164626/207255664-ffb9901d-8b50-4625-9137-0d5718429cfe.png)
width、heightの指定はレイアウトが崩れる原因となるので、避けましょう！

2022-12-13 08:06 UTC, SakaueYae commented on src/components/organisms/top/top.scss
> +      padding: 32px 161px 20px 161px;
このpaddingはfigmaの値から取ってきてくださったのだと思いますが、画面幅が狭くなった時に見た目が崩れてしまうため、削除してもらって大丈夫です！

2022-12-13 08:06 UTC, SakaueYae commented on src/components/organisms/top/top.html
> +    </p>
ここは1つのpタグにまとめた方が良いと思います。

2022-12-17 07:40 UTC, moe-backend reviewed
コメントしました！！

2022-12-17 07:40 UTC, moe-backend commented on src/components/organisms/top/top.scss
> +      background-position: -20px;
ここで画像が左にずれてしまっているので、プロパティの値を0にして元の位置に戻しましょう！！
↓参考にしてください。
https://developer.mozilla.org/ja/docs/Web/CSS/background-position

2022-12-17 07:40 UTC, moe-backend commented on src/components/organisms/top/top.scss
> +    .message {
paddingの修正をお願いします！

2022-12-22 11:32 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/209125245-db3d9c97-2edd-4796-950e-20e4212de6c6.png)
Figma見てみると分かるのですが、titleがmessageよりも幅をとることはなさそうです。messageの構造をもう一度もとに戻してみてから、Figmaと見比べて確認して見てください！

2022-12-22 11:33 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/209125577-52a1b5c6-9976-4636-bc3d-44937154e416.png)
ここは下のpaddingも32pxだと思います。Figmaを確認して見てください！

2022-12-22 11:34 UTC, MinamiHotta reviewed
少々あいまいな言い方が多くなってしまい申し訳ありません💦
不明点あればすぐ教えてください！

2022-12-22 11:34 UTC, MinamiHotta commented on src/components/organisms/top/top.scss
> +      background-position: 0px 0px;
こちら、検証ツールで付け外ししてみても効いていなさそうなのですが、どうでしょう？

2022-12-22 11:34 UTC, MinamiHotta commented on src/components/organisms/top/top.scss
> +  }
messageについては、Molecules/Messageをそのまま使うので、余白以外はほぼいじらなくてもできるはずなのですが、いかがでしょうか？

2022-12-22 11:34 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> -    padding: 32px 20px;
現行のこのままでいきたいです

2022-12-26 15:12 UTC, renyagi commented on src/components/organisms/top/top.scss
> +
molecules/message を使うと記述量が減ると思います！

2022-12-26 15:12 UTC, renyagi commented on src/components/organisms/top/top.scss
> +    background-image: url(../../../img/top.jpg);
<img width="555" alt="スクリーンショット 2022-12-27 000103" src="https://user-images.githubusercontent.com/105191030/209562083-f50d1229-9258-4ff1-b334-11914a22a166.png">
画面幅を小さくしたときに空白ができているので修正お願いします。
おそらく画像はhtmlのほうでimgタグをつくって貼ったほうが良いと思います。

参考
https://developer.mozilla.org/ja/docs/Web/CSS/object-fit

2022-12-28 11:50 UTC, tomonariasai commented on src/components/organisms/top/top.scss
> +.top {
![image](https://user-images.githubusercontent.com/104602415/209805764-1af5f0d8-026c-47a2-98a3-620078ce4270.png)

2022-12-28 11:50 UTC, tomonariasai commented on src/components/organisms/top/top.scss
> +.top {
この部分なのですが、sectionタグにmargin 120pxが効いてしまっていると思います。
![image](https://user-images.githubusercontent.com/104602415/209806182-730bbab4-8924-420a-ad6f-c9fa6aff3853.png)

2022-12-28 11:50 UTC, tomonariasai commented on src/components/organisms/top/top.scss
> +.top {
figmaだと上の写真(md以下のとき)のように　md以下ではmargin 40px 、lgより大きいとmargin 30pxになっていると思います。確認お願いいたします

2022-12-28 12:15 UTC, tomonariasai commented
![image](https://user-images.githubusercontent.com/104602415/209810759-aa664484-05d5-467f-a297-b0c138536207.png)

2022-12-30 02:35 UTC, renyagi commented on src/components/organisms/top/top.scss
> +    padding: 52px 0px 74px;
paddingの横幅が間違っています🌓

2023-01-01 15:43 UTC, renyagi commented
<img width="418" alt="スクリーンショット 2023-01-02 004052" src="https://user-images.githubusercontent.com/105191030/210176557-77bf5514-df2d-4e60-8bc9-1bb06e0eb53f.png">
lgでの「カフェで読書＆～」の横幅の修正だけお願いします👓

2023-01-02 03:17 UTC, higashiji2000 commented on src/components/organisms/top/top.scss
> +      padding-top: 75%;
> ・md以下の時は画像の高さは360px固定、lg以上の時はウィンドウの高さいっぱいになるようにお願いします。

↑のような指定があるので、高さをウインドウの高さいっぱいになるようにお願いします。
画面幅を基準に指定するための単位があるので、それを height に指定すればいいと思います。

2023-01-02 03:31 UTC, higashiji2000 requested changes
基本的にOKです！画像を画面の高さにするというところだけ修正必須でお願いします！

2023-01-02 03:31 UTC, higashiji2000 commented on src/components/organisms/top/top.scss
> +        width: 670px;
下位コンポーネントのスタイルを、使う側で上書きするのはスタイルの把握が難しくなるため基本的にはあまり推奨されません。（今回でも追加で必要な記述は色くらいのはずです。）
何か表示に不都合があれば、そもそも message.scss が間違っていないかも確認してみてください。

2023-01-02 03:31 UTC, higashiji2000 commented on src/components/organisms/top/top.scss
> +    }
これ一つの要素にまとめられるかもですね！

2023-01-02 03:31 UTC, higashiji2000 commented on src/components/organisms/top/top.scss
> +  }
```suggestion
  .message {
    background-color: $black;
    img: $white;
  }
```
これでもいいかもしれません。（message.scssの書き方によってはこれではダメかも）

2023-01-02 03:50 UTC, Kotaro0722 commented on src/components/organisms/top/top.scss
> +  }
うまくいきませんでした

2023-01-05 05:10 UTC, higashiji2000 approved these changes
LGTMです！

2023-01-05 05:10 UTC, merged