Organisms about
shinonome-inc/Kotaro-frontend-basic-last-assignment pull request #11
Opened 2022-12-10 06:46 UTC by Kotaro0722

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[](https://62c82af834e6e12f9fe007c7-plnxbzsknx.chromatic.com/?path=/story/organisms-about--about)

2022-12-14 16:04 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/207645856-eeb9fb11-add9-4f92-a21c-5a7494b390de.png)
widthが固定になっている関係で、左に寄ってしまっています。
bootstrapのcontainerを使う形で書き直していただくのが早いかなと思います！

また、不要なコードがないか軽くチェックいただけるとより良いかなと思います 🌭

2022-12-14 16:04 UTC, Higashiji commented on src/components/organisms/about/about.scss
> +    width: 991px;
左右の幅および左右の余白に関しては、figmaの通り固定値で持つ必要はありません。
<img width="757" alt="スクリーンショット 2022-12-15 0 54 31" src="https://user-images.githubusercontent.com/83479175/207644431-1e6f3013-dad2-4b14-bf67-9b0c7d58a337.png">

bootstrapの container を使うと、左右の余白および中央揃えを行なってくれます。
基本的にはこれを使うのをお勧めします。 
doc: https://getbootstrap.jp/docs/5.0/layout/containers/

figmaで全ての画面幅の表示を網羅することはできないので、デザイナーの意図を汲み取って実装するというのは案件でも必要なスキルかなと思います！

2022-12-14 16:04 UTC, Higashiji commented on src/components/organisms/about/about.scss
> +          transform: scale(calc(360 / 295));
![image](https://user-images.githubusercontent.com/83479175/207645211-0185ed13-4109-4f03-96dd-1ddd864cc498.png)
画像の大きさを揃える意図でしたら、width: 100% にすればOKです！

2022-12-14 16:04 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +    }
.messageのスタイルは、基本的にmolecules/messageをそのまま使うので問題ないはずです。
追加で指定する必要があるのは色くらいかなと思います！

2022-12-14 16:04 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +          transform: scale(calc(360 / 295));
見た目は現状で問題ないので修正はしなくても大丈夫です。

2022-12-25 12:48 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/209468493-e29fb071-f05e-45c2-a4c1-b67d6d6f228c.png)
上部にも余白がつけられるとよいと思います

2022-12-25 12:50 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/209468534-929378ec-e2b8-4e03-9472-dc4cef98d199.png)
lg以上の画面サイズのaboutの外の余白を見直してみてください（最近講師側で追記＆変更した部分なので対応お願いします💦）

2022-12-25 13:19 UTC, MinamiHotta reviewed
修正お願いします🔥

2022-12-25 13:19 UTC, MinamiHotta commented on src/components/organisms/about/about.html
> +    </p>
ここは改行の`<br>`を用いて
`<p class="explanation-text">月額プラン以外にビジター料金でのご利用も可能です。通いやすい時間や曜日に合わせてプランをお選びください。<br>ご登録プランは後の変更も可能ですので、資格試験等の目標がある場合など環境の変化に合わせて柔軟に対応しております。WiFiも電源も標準設備しており、<br>時間を気にせず仕事や勉強に取り組めます。カフェでの長居は気が引けるという方にも心置きなくご利用いただけます</p>`　とするのが望ましいです！

2022-12-25 13:19 UTC, MinamiHotta commented on src/components/organisms/about/about.scss
> +          transform: scale(calc(360 / 295));
marginとtransformはなくしてしまってよいです！
これは何か意図があったのでしょうか、、？

2022-12-25 13:19 UTC, MinamiHotta commented on src/components/organisms/about/about.scss
> +          transform: scale(calc(360 / 295));
画面サイズmdでこれらをなくすことで、横幅がずれてしまうと思うので、`width:100%`をいれてみてください！

2022-12-25 13:19 UTC, MinamiHotta commented on src/components/organisms/about/about.html
> +<div class="about container-fluid">
こちら自前の`container-fluid`ではなくbootstrapの`container`を使っていただいて、padding等はなしにしてOKです！

2022-12-25 13:19 UTC, MinamiHotta commented on src/components/organisms/about/about.html
> +  </div>
`<div class="img-grp">`
は削って（画像4枚を2枚ずつではなく一塊で扱った方がよいため）
`<div class="img-group"></div>`　の中に画像を4つ入れる形にし、img-groupクラスにcss gridというものを導入して画像を見本通りに並べてみてください！

2022-12-26 03:06 UTC, renyagi commented on src/components/organisms/about/about.scss
> +      img {
Reset viewpointで画面幅を変えたときに写真が見切れてしまっています。
おそらくwidthのpxでしていしまっているのが原因なので変更お願いします！

2022-12-26 03:06 UTC, renyagi commented on src/components/organisms/about/about.scss
> +
せっかくなのでmolecules/messageを使ったほうが良いと思います！

2022-12-31 13:48 UTC, higashiji2000 approved these changes
LGTMです 👨‍🎓

2022-12-31 13:48 UTC, higashiji2000 commented on src/components/organisms/about/about.html
> +    <img src="../../../img/about-4.jpg" alt="" />
altを空文字列にしている点、理解度が高くてGoodです！

2022-12-31 13:48 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +    max-width: 990px;
`.container`ついているので、max-width に関してはそちらに任せてもいいのかなと思います。
あったらダメということはないので今回はOKです！

2022-12-31 13:48 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +        width: 240px;
```suggestion
        flex: 1;
        min-width: 0;
```
親要素がflexなのでこうするとwidthを固定にしなくても等幅が実現できます。
min-widthを指定しているのは親要素をはみ出さないためで、以下の記事が詳しく説明しています。
https://qiita.com/mpyw/items/dfc63c1fed5dfc5eda26

2023-01-01 07:22 UTC, merged