Organisms-Cards
shinonome-inc/Kotaro-frontend-basic-last-assignment pull request #12
Opened 2022-12-11 02:06 UTC by Kotaro0722

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[](chromatic上の該当ページへのリンクを貼る)

2022-12-14 02:12 UTC, moe-backend commented
CONCEPTのカードの文を2文にせず、1文にまとめて途中で＜br＞で改行すると行間がきれいに揃うと思います！！

2022-12-14 07:03 UTC, higashiji2000 requested changes

2022-12-14 07:03 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +    background-color: #f5f5f5;
色は変数使っていきましょう！

2022-12-14 07:03 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +      font-size: 14px;
ここも変数だとGoodです。

2022-12-14 07:03 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +        transform: scale(1.2, 1.2);
```suggestion
        transform: scale(1.2);
```
縦横の拡大比率が同じな時はこの書き方で問題ないです。

2022-12-14 07:03 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +    font-size: 20px;
ここも変数です

2022-12-14 07:03 UTC, Higashiji commented on src/components/organisms/cards/cards.scss
> +    padding: 0px 113px;
検証ツールでモバイル端末をエミュレートしたのが下の画像ですが、paddingが広すぎるみたいです。
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/83479175/207525917-4500e94c-2bd8-43c3-a913-bcd13074d431.png">


bootstrapのcontainerを利用すると左右の余白を画面幅に応じて変更してくれるので、これを使っていけるといい感じです。
https://getbootstrap.jp/docs/5.0/layout/containers/

2022-12-14 07:03 UTC, higashiji2000 commented on src/components/organisms/cards/cards.html
> +<div class="card-group">
```suggestion
<div class="card-group container">
```
containerはこんな感じで親の要素に設定するので問題ないと思います。

2022-12-14 07:03 UTC, higashiji2000 commented on src/components/organisms/cards/cards.scss
> +      height: 264px;
heightを画面幅に応じて px で指定していただいていると思うのですが、この必要はないかと思います。
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/83479175/207526975-4584116c-8436-495d-af30-bfdaca94d925.png">

画像は検証ツールでheightの指定を無効化してみたときの表示ですが、これでも問題がないことがわかります。

2022-12-22 13:08 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/209140895-0d1709f3-7076-47b4-9776-33f3304805db.png)
ここのずれているのが気になるので、全部のカードに`flex:1;`をあててみましょう！
下が揃うはずです。

2022-12-23 06:04 UTC, MinamiHotta commented on src/components/organisms/cards/cards.scss
> +    padding: 0px 113px;
containerを使うときは、paddingの設定は不要です！
完成イメージはこんな感じです
![image](https://user-images.githubusercontent.com/104500220/209136195-6c0f514f-581e-4f4a-9abc-3faa4a58f180.png)

2022-12-25 12:44 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/209468344-b9a9710f-8486-4053-a4b9-61b4a1048a0f.png)
画面サイズmd以上のときのmargin-bottomがなかったので（確認漏れだったらすみません）Figmaを参考につけるようお願いします！

2022-12-25 13:33 UTC, MoAI522 commented on src/components/organisms/cards/cards.scss
> +  }
この二つのメディアクエリ分ける意味がそんなにないのでまとめましょう！

2022-12-25 13:33 UTC, MoAI522 commented on src/components/organisms/cards/cards.scss
> +    gap: 24px;
gap等、いちいち指定しなくても他の場所で効いてる指定は極力削りましょう。これが邪魔で消したくなった時にどこを消せばいいか分かりづらくなるので。

2022-12-25 13:33 UTC, MoAI522 commented on src/components/organisms/cards/cards.scss
> +  }
HTML/CSS課題は「デスクトップファースト」のレスポンシブ対応をしましょう。すなわち、CSSは上から
- 画面幅が大きいとき（lgよりでかい）用のスタイル（デフォルト）
- 画面幅がlg以下のときのスタイル（メディアクエリ）
- 画面幅がmd以下のときのスタイル（メディアクエリ）
- 画面幅がsm以下のときのスタイル（メディアクエリ）
といった順で記述していきましょう。（パーツによっては対応する必要のない画面幅があります。）
今書いてくださってるのは順番が逆＆xl以上のときの指定をデフォルトのスタイルにするべき、です。

2022-12-27 12:18 UTC, renyagi commented
ok

2022-12-28 04:08 UTC, MoAI522 approved these changes
LGTM

2022-12-28 04:09 UTC, merged