page
shinonome-inc/Kotaro-frontend-basic-last-assignment pull request #17
Opened 2023-01-23 02:05 UTC by Kotaro0722

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[http://shinonome.io/Kotaro-frontend-basic-last-assignment/](http://shinonome.io/Kotaro-frontend-basic-last-assignment/)

2023-01-29 18:01 UTC, caramelribon commented
- お手本サイトのようにheaderと画像が重なるようにしてください！

https://demo.tcd-theme.com/tcd063/

- また、画面幅が一番おおきいときのheaderの幅がなぜか途中できれているので、画面幅いっぱいになるようにおねがいします！

![スクリーンショット (1086)](https://user-images.githubusercontent.com/91133956/215346201-df11a38b-731a-46cc-92b0-9ee4e5973507.png)

- あと、aboutとcardの間にmarginがないのでを入れるようにしましょう！

![スクリーンショット (1087)](https://user-images.githubusercontent.com/91133956/215346207-0cb8bb35-df98-49ac-ace2-72eb801f3347.png)

2023-02-04 11:12 UTC, ssshun3 commented
Templates/NewsAndEventsに背景色の指定をお願いします。画面幅lg以上の時のaboutとcardsの間のmarginの値が違います。
footerの部分のDOWNLOADの右隣の「|」は必要ないです
![image](https://user-images.githubusercontent.com/110015394/216763969-56c3b0b9-5c59-433b-a300-e3ce1ec4fc0a.png)
wakanaさんが指摘された
> * お手本サイトのようにheaderと画像が重なるようにしてください！

の修正もお願いします。
こちらの[ページ](https://demo.tcd-theme.com/tcd063/)か「ページを完成させる」にある画像と見比べながら作業すると上手く実装できると思います。

2023-02-05 05:44 UTC, tomonariasai reviewed
・headerがxl以上のときplus-iconが右の変な位置表示されてしまっていると思います。確認お願いします。
また、headerがlg以下のときに下の写真みたいに縮んでしまっているみたいです。画面いっぱい横にひろがるようにお願い致します。
![image](https://user-images.githubusercontent.com/104602415/216804069-0198dc18-d9d6-423e-8a27-b63cb7d8d7e5.png)

・ssshun3さんが指摘された
「画面幅lg以上の時はaboutとcardsの間のmarginの値は100pxにしてください。」の修正お願いします。


・Templates/NewsAndEventsの背景色は横幅全体に広がるように確認お願いします
現在以下のような感じです。
![image](https://user-images.githubusercontent.com/104602415/216804750-55b3c36b-899a-4300-bcd4-b1d7c7d57565.png)
下の感じになるようにお願いしたいです。
![image](https://user-images.githubusercontent.com/104602415/216804787-80f6ffbb-e105-401e-be33-93655d7ba164.png)

2023-02-08 14:24 UTC, AyumuTaoka commented on src/components/organisms/about/about.scss
> +  margin-bottom: 100px;
aboutはブレイクポイントでmargin-bottomが違うので修正お願いします

2023-02-11 14:07 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/218262207-4dcf74d7-b9f8-4775-a85c-4823d1d31aa8.png)
画面幅が広いと、headerのナビゲションが左に寄った感じになっています。
[元サイト](https://demo.tcd-theme.com/tcd063/)を参考に修正をお願いします。

---
![image](https://user-images.githubusercontent.com/83479175/218262343-4dca5687-c82d-4038-bea7-fc6a27e71f1b.png)
ヘッダーの下端とドロップダウンの上端がズレているので、これもピッタリなるようにしましょう。

2023-02-12 14:57 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/218318262-ab80d4c0-a66f-41a4-b034-ebc1603e663d.png)
![image](https://user-images.githubusercontent.com/83479175/218318320-2fdcbe94-1b24-4173-b651-9406f56fb6c3.png)

dropdownの表示位置をfigmaに近づけてください。

---

![image](https://user-images.githubusercontent.com/83479175/218318361-2873de2e-8873-45e5-8263-53ef57a764fd.png)
メニューにホバーしたときに灰色にするのも対応お願いします。
こちら画面サイズがxl以上のときだけなので注意してください！

---

なお、 `a` 要素に `href` 属性を設定すると `cursor: pointer` が適用されます。
今回は修正範囲が大きすぎるので必須とはしませんが、以降 `a` タグを使うときは、 `href="#"` みたいな感じでダミーの値を入れておくことをおすすめします！

2023-02-16 02:54 UTC, higashiji2000 requested changes

2023-02-16 02:54 UTC, higashiji2000 commented on src/components/organisms/header/header.scss
> +            left: 584px;
![image](https://user-images.githubusercontent.com/83479175/219255429-aa896a6b-d552-4c63-bc40-2edad9625c76.png)
画面全体を基準に絶対値指定をしているため、大きいディスプレイでは表示が崩れてしまっています。
これを防ぐため、 `position: relative` によって位置指定の基準となる要素を設定しましょう。

今回の例では、`ul`の親要素である下画像の要素に設定するのがgoodです
![image](https://user-images.githubusercontent.com/83479175/219255541-da680dda-91e1-4f72-b4a8-e68b8ed6233a.png)

2023-02-17 02:33 UTC, higashiji2000 approved these changes
![LGTM](https://image.lgtmoon.dev/116936)

2023-02-17 02:34 UTC, merged